import tkinter as tk
root = tk.Tk()
root.title("Menu Example")
menu_bar = tk.Menu(root)
file_menu = tk.Menu(menu_bar, tearoff=0)
file_menu.add_command(label="New")
file_menu.add_command(label="Open")
file_menu.add_command(label="Exit", command=root.quit)
menu_bar.add_cascade(label="File", menu=file_menu)
root.config(menu=menu_bar)
menubutton = tk.Menubutton(root, text="Options", relief="raised")
menubutton.pack()
mb_menu = tk.Menu(menubutton, tearoff=0)
mb_menu.add_command(label="Option 1")
mb_menu.add_command(label="Option 2")
menubutton.config(menu=mb_menu)
root.mainloop()
